In [4]:
import numpy as np
import pandas as pd

In [5]:
df=pd.read_csv("../data/raw/ecommerce_retail_transactions_raw.csv")

In [6]:
df.head()

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating
0,ORD011416,CUST00003,2026-04-03,Books,Self-Help Book,3,9.16,5.0,Net Banking,London,UK,Delivered,5.0
1,ORD000974,CUST00269,10-15-2024,Books,Fiction Novel,1,34.24,5.0,NetBanking,Toronto,CA,Shipped,NaN
2,ORD000617,CUST02075,17 Jun 2024,Home & Kitchen,Vacuum Cleaner,2,111.95,15.0,DEBIT CARD,Brisbane,Australia,Shipped,NaN
3,ORD006437,CUST02109,16/10/2025,Beauty,Hair Dryer,1,31.84,0.0,Cash on Delivery,Birmingham,U.K.,Delivered,3.0
4,ORD000740,CUST00349,06 Apr 2026,Home & Kitchen,Non-Stick Pan,2,72.00,NaN,Credit_Card,Montreal,CA,Delivered,NaN

In [7]:
df.shape

(12180, 13)

In [8]:
for i in range(len(df.columns)):
    print(df.columns[i])

Order_ID
Customer_ID
Order_Date
Product_Category
Product_Name
Quantity
Unit_Price_USD
Discount_Percent
Payment_Method
Shipping_City
Country
Order_Status
Customer_Rating

In [9]:
df["Order_ID"].nunique()

12000

In [10]:
df.nunique()

Order_ID            12000
Customer_ID          3374
Order_Date           4229
Product_Category        8
Product_Name           46
Quantity                7
Unit_Price_USD       7791
Discount_Percent        6
Payment_Method         20
Shipping_City          22
Country                24
Order_Status            5
Customer_Rating         5
dtype: int64

In [11]:
df["Customer_ID"].nunique()

3374

In [12]:
df.duplicated().sum()

np.int64(180)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          12180 non-null  object
 1   Customer_ID       12180 non-null  object
 2   Order_Date        12180 non-null  object
 3   Product_Category  12180 non-null  object
 4   Product_Name      12180 non-null  object
 5   Quantity          12180 non-null  int64
 6   Unit_Price_USD    12180 non-null  float64
 7   Discount_Percent  11445 non-null  float64
 8   Payment_Method    12180 non-null  object
 9   Shipping_City     11678 non-null  object
 10  Country           12180 non-null  object
 11  Order_Status      12180 non-null  object
 12  Customer_Rating   6030 non-null   float64
dtypes: float64(3), int64(1), object(9)
memory usage: 1.2+ MB

In [14]:
df["Order_Date"].head()

0     2026-04-03
1     10-15-2024
2    17 Jun 2024
3     16/10/2025
4    06 Apr 2026
Name: Order_Date, dtype: object

In [15]:
df["Payment_Method"].value_counts(dropna=False)

Payment_Method
paypal              709
net banking         708
PayPal              695
UPI                 692
Net Banking         690
DEBIT CARD          680
NetBanking          658
U.P.I               651
Pay Pal             649
debit card          632
Debit Card          627
upi                 622
COD                 542
CREDIT CARD         538
cash on delivery    531
cod                 525
Credit_Card         517
credit card         508
Cash on Delivery    503
Credit Card         503
Name: count, dtype: int64

In [16]:
df["Country"].value_counts(dropna=False)

Country
UAE               609
australia         599
DE                596
Germany           592
U.A.E             588
IN                588
germany           587
Australia         586
india             584
uae               579
canada            569
AU                550
CA                550
India             547
Canada            538
uk                461
U.K.              448
United Kingdom    442
UK                433
usa               370
USA               365
United States     346
US                342
U.S.A             311
Name: count, dtype: int64

In [17]:
df[["Quantity","Unit_Price_USD","Discount_Percent","Customer_Rating"]].describe()

           Quantity  Unit_Price_USD  Discount_Percent  Customer_Rating
count  12180.000000     12180.00000      11445.000000      6030.000000
mean       2.019458        61.55069          7.299257         3.896186
std        1.234956        52.53839          7.120143         1.113482
min       -1.000000         3.01000          0.000000         1.000000
25%        1.000000        22.02000          0.000000         3.000000
50%        2.000000        42.76500          5.000000         4.000000
75%        3.000000        87.71250         10.000000         5.000000
max        5.000000       249.84000         25.000000         5.000000

In [18]:
df.isnull().sum()

Order_ID               0
Customer_ID            0
Order_Date             0
Product_Category       0
Product_Name           0
Quantity               0
Unit_Price_USD         0
Discount_Percent     735
Payment_Method         0
Shipping_City        502
Country                0
Order_Status           0
Customer_Rating     6150
dtype: int64

In [19]:
(df.isnull().mean()*100).round(2)

Order_ID             0.00
Customer_ID          0.00
Order_Date           0.00
Product_Category     0.00
Product_Name         0.00
Quantity             0.00
Unit_Price_USD       0.00
Discount_Percent     6.03
Payment_Method       0.00
Shipping_City        4.12
Country              0.00
Order_Status         0.00
Customer_Rating     50.49
dtype: float64

In [20]:
df["Order_Status"].value_counts()

Order_Status
Delivered    6673
Shipped      1848
Pending      1416
Cancelled    1207
Returned     1036
Name: count, dtype: int64

missing investigation

In [21]:
df[df["Discount_Percent"].isna()].head()

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating
4,ORD000740,CUST00349,06 Apr 2026,Home & Kitchen,Non-Stick Pan,2,72.00,NaN,Credit_Card,Montreal,CA,Delivered,NaN
7,ORD011407,CUST00135,10/07/2024,Books,Cookbook,3,37.49,NaN,Cash on Delivery,New York,USA,Returned,NaN
8,ORD005427,CUST00945,19/08/2025,Home & Kitchen,Vacuum Cleaner,4,21.44,NaN,NetBanking,Los Angeles,USA,Shipped,NaN
19,ORD011697,CUST02152,04-16-2026,Fashion,Cotton T-Shirt,3,86.68,NaN,Pay Pal,Munich,DE,Shipped,NaN
21,ORD009446,CUST01424,17 Oct 2024,Sports,Football,1,53.17,NaN,upi,Melbourne,AU,Delivered,5.0

In [22]:
pd.crosstab(
    df["Order_Status"],
    df["Discount_Percent"].isna(),
    normalize="index"
).round(3)

Discount_Percent  False  True
Order_Status
Cancelled         0.948  0.052
Delivered         0.939  0.061
Pending           0.949  0.051
Returned          0.939  0.061
Shipped           0.929  0.071

In [23]:
pd.crosstab(
    df["Product_Category"],
    df["Discount_Percent"].isna(),
    normalize="index"
)

Discount_Percent     False     True
Product_Category
Beauty            0.925166  0.074834
Books             0.949742  0.050258
Electronics       0.930989  0.069011
Fashion           0.941520  0.058480
Grocery           0.942991  0.057009
Home & Kitchen    0.941327  0.058673
Sports            0.944368  0.055632
Toys              0.940912  0.059088

In [24]:
df[df["Shipping_City"].isna()].head(20)

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating
34,ORD003182,CUST02431,2024-11-06,Beauty,Sunscreen SPF50,1,58.51,0.0,COD,NaN,UK,Shipped,NaN
42,ORD001098,CUST02792,27 Apr 2025,Books,Fiction Novel,4,12.28,0.0,Credit_Card,NaN,United States,Delivered,4.0
56,ORD002014,CUST00395,28/01/2025,Home & Kitchen,Vacuum Cleaner,1,106.12,NaN,debit card,NaN,USA,Delivered,5.0
132,ORD006138,CUST01368,2024/03/13,Beauty,Hair Dryer,3,50.45,10.0,COD,NaN,canada,Delivered,5.0
164,ORD004007,CUST02743,13 Apr 2025,Beauty,Perfume,3,32.20,10.0,debit card,NaN,Canada,Delivered,4.0
186,ORD010738,CUST01848,06-29-2024,Grocery,Almonds 500g,2,4.70,5.0,NetBanking,NaN,Germany,Shipped,NaN
208,ORD000339,CUST00893,03-05-2024,Beauty,Lipstick,2,21.36,0.0,Credit_Card,NaN,Australia,Delivered,4.0
266,ORD006280,CUST02064,10/08/2025,Toys,Building Blocks Set,2,28.84,5.0,paypal,NaN,uae,Shipped,NaN
273,ORD000856,CUST02332,10-20-2025,Sports,Dumbbell Set,3,29.00,15.0,CREDIT CARD,NaN,United States,Cancelled,NaN
343,ORD007614,CUST00392,2024/10/29,Fashion,Leather Wallet,1,97.80,0.0,DEBIT CARD,NaN,USA,Delivered,NaN
352,ORD011680,CUST00369,2024-10-25,Books,Cookbook,4,25.33,0.0,Pay Pal,NaN,DE,Cancelled,NaN
432,ORD011336,CUST00600,02-19-2026,Beauty,Perfume,4,28.20,5.0,DEBIT CARD,NaN,DE,Delivered,4.0
436,ORD006238,CUST02295,12-01-2024,Books,Self-Help Book,1,18.55,NaN,DEBIT CARD,NaN,United States,Returned,NaN
491,ORD002290,CUST02588,2025-04-02,Toys,Building Blocks Set,1,56.29,0.0,COD,NaN,UK,Delivered,3.0
517,ORD009050,CUST00729,22 May 2026,Electronics,Laptop Stand,2,177.16,5.0,PayPal,NaN,DE,Delivered,5.0
530,ORD006450,CUST01469,10-02-2025,Sports,Football,2,83.85,0.0,COD,NaN,United Kingdom,Delivered,4.0
531,ORD004033,CUST02392,2024/06/17,Grocery,Basmati Rice 5kg,1,27.41,NaN,cash on delivery,NaN,AU,Delivered,4.0
532,ORD009977,CUST01212,03-02-2024,Toys,Action Figure,2,84.74,0.0,Pay Pal,NaN,India,Delivered,3.0
572,ORD011591,CUST01397,2025/04/23,Books,Fiction Novel,3,32.51,5.0,Credit Card,NaN,U.S.A,Delivered,5.0
617,ORD008622,CUST01212,2025-10-04,Sports,Dumbbell Set,4,110.78,10.0,COD,NaN,CA,Delivered,4.0

In [25]:
pd.crosstab(
    df["Order_Status"],
    df["Shipping_City"].isna(),
    normalize="index"
)

Shipping_City     False     True
Order_Status
Cancelled      0.962717  0.037283
Delivered      0.958639  0.041361
Pending        0.951977  0.048023
Returned       0.967181  0.032819
Shipped        0.957251  0.042749

In [26]:
df[df["Customer_Rating"].isna()].head(20)

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating
1,ORD000974,CUST00269,10-15-2024,Books,Fiction Novel,1,34.24,5.0,NetBanking,Toronto,CA,Shipped,NaN
2,ORD000617,CUST02075,17 Jun 2024,Home & Kitchen,Vacuum Cleaner,2,111.95,15.0,DEBIT CARD,Brisbane,Australia,Shipped,NaN
4,ORD000740,CUST00349,06 Apr 2026,Home & Kitchen,Non-Stick Pan,2,72.00,NaN,Credit_Card,Montreal,CA,Delivered,NaN
6,ORD002861,CUST01324,21/03/2026,Fashion,Formal Shirt,1,18.34,5.0,upi,Brisbane,Australia,Cancelled,NaN
7,ORD011407,CUST00135,10/07/2024,Books,Cookbook,3,37.49,NaN,Cash on Delivery,New York,USA,Returned,NaN
8,ORD005427,CUST00945,19/08/2025,Home & Kitchen,Vacuum Cleaner,4,21.44,NaN,NetBanking,Los Angeles,USA,Shipped,NaN
9,ORD002304,CUST02603,07-14-2025,Sports,Dumbbell Set,1,20.77,10.0,Pay Pal,Munich,germany,Cancelled,NaN
10,ORD006172,CUST00940,06-05-2024,Books,Kids Storybook,3,37.22,5.0,debit card,Melbourne,Australia,Delivered,NaN
12,ORD006143,CUST01216,11 Jun 2025,Toys,Remote Control Car,2,50.78,0.0,Credit_Card,Manchester,UK,Shipped,NaN
13,ORD002406,CUST00026,12-09-2024,Toys,Action Figure,1,14.44,0.0,COD,Montreal,canada,Shipped,NaN
15,ORD000325,CUST02081,15 Jul 2025,Electronics,Webcam,1,121.61,0.0,Credit Card,Delhi,IN,Cancelled,NaN
19,ORD011697,CUST02152,04-16-2026,Fashion,Cotton T-Shirt,3,86.68,NaN,Pay Pal,Munich,DE,Shipped,NaN
27,ORD010531,CUST03205,2024/12/25,Sports,Yoga Mat,1,18.37,20.0,debit card,Berlin,Germany,Shipped,NaN
28,ORD007093,CUST00950,2024-02-20,Home & Kitchen,Blender,1,168.65,0.0,net banking,Chicago,usa,Pending,NaN
29,ORD001920,CUST00612,21 Jan 2024,Fashion,Formal Shirt,2,25.13,0.0,cod,Bengaluru,india,Shipped,NaN
30,ORD011670,CUST01862,2024-11-17,Electronics,Wireless Earbuds,2,204.37,15.0,Debit Card,Abu Dhabi,U.A.E,Cancelled,NaN
31,ORD007969,CUST01835,04-20-2026,Grocery,Green Tea Pack,5,6.17,5.0,cash on delivery,Berlin,DE,Cancelled,NaN
32,ORD005584,CUST02197,07/02/2024,Fashion,Formal Shirt,1,118.48,25.0,U.P.I,Dubai,uae,Pending,NaN
34,ORD003182,CUST02431,2024-11-06,Beauty,Sunscreen SPF50,1,58.51,0.0,COD,NaN,UK,Shipped,NaN
37,ORD008127,CUST00559,28 Aug 2024,Grocery,Green Tea Pack,2,16.30,10.0,PayPal,Sydney,Australia,Cancelled,NaN

In [27]:
pd.crosstab(
    df["Order_Status"],
    df["Customer_Rating"].isna(),
    normalize="index"
).round(3)

Customer_Rating  False  True
Order_Status
Cancelled        0.000  1.000
Delivered        0.904  0.096
Pending          0.000  1.000
Returned         0.000  1.000
Shipped          0.000  1.000

duplicate investigation

In [28]:
df.duplicated().sum()

np.int64(180)

In [29]:
df[df.duplicated(keep=False)].sort_values(by="Order_ID").head(20)

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating
10813,ORD000018,CUST00794,07-20-2024,Books,Kids Storybook,2,23.28,15.0,DEBIT CARD,Bengaluru,India,Shipped,NaN
9400,ORD000018,CUST00794,07-20-2024,Books,Kids Storybook,2,23.28,15.0,DEBIT CARD,Bengaluru,India,Shipped,NaN
4476,ORD000036,CUST00063,04 May 2026,Electronics,Power Bank,1,31.76,5.0,Pay Pal,Toronto,CA,Delivered,4.0
6580,ORD000036,CUST00063,04 May 2026,Electronics,Power Bank,1,31.76,5.0,Pay Pal,Toronto,CA,Delivered,4.0
7763,ORD000136,CUST00688,27 Sep 2024,Fashion,Sunglasses,2,54.91,15.0,net banking,Sydney,australia,Delivered,4.0
952,ORD000136,CUST00688,27 Sep 2024,Fashion,Sunglasses,2,54.91,15.0,net banking,Sydney,australia,Delivered,4.0
881,ORD000283,CUST02279,04 May 2026,Beauty,Face Moisturizer,1,9.40,NaN,UPI,Manchester,uk,Delivered,4.0
108,ORD000283,CUST02279,04 May 2026,Beauty,Face Moisturizer,1,9.40,NaN,UPI,Manchester,uk,Delivered,4.0
2941,ORD000385,CUST02389,08-29-2025,Fashion,Hoodie,2,13.65,5.0,COD,Brisbane,AU,Delivered,4.0
4518,ORD000385,CUST02389,08-29-2025,Fashion,Hoodie,2,13.65,5.0,COD,Brisbane,AU,Delivered,4.0
11684,ORD000449,CUST00883,2026-02-15,Toys,Action Figure,2,15.20,10.0,debit card,Bengaluru,IN,Delivered,5.0
6204,ORD000449,CUST00883,2026-02-15,Toys,Action Figure,2,15.20,10.0,debit card,Bengaluru,IN,Delivered,5.0
11321,ORD000479,CUST01977,31/10/2025,Books,Self-Help Book,1,31.96,0.0,U.P.I,Munich,Germany,Shipped,NaN
11588,ORD000479,CUST01977,31/10/2025,Books,Self-Help Book,1,31.96,0.0,U.P.I,Munich,Germany,Shipped,NaN
11388,ORD000491,CUST01866,08/07/2025,Sports,Cricket Bat,3,116.29,0.0,Credit_Card,London,U.K.,Delivered,4.0
11155,ORD000491,CUST01866,08/07/2025,Sports,Cricket Bat,3,116.29,0.0,Credit_Card,London,U.K.,Delivered,4.0
2280,ORD000587,CUST03217,06 Dec 2025,Grocery,Olive Oil 1L,3,14.31,0.0,cod,Vancouver,CA,Shipped,NaN
1080,ORD000587,CUST03217,06 Dec 2025,Grocery,Olive Oil 1L,3,14.31,0.0,cod,Vancouver,CA,Shipped,NaN
10675,ORD000663,CUST00557,08 Apr 2026,Fashion,Hoodie,2,18.88,0.0,Debit Card,Delhi,IN,Delivered,5.0
4172,ORD000663,CUST00557,08 Apr 2026,Fashion,Hoodie,2,18.88,0.0,Debit Card,Delhi,IN,Delivered,5.0

In [30]:
df["Order_ID"].nunique()

12000

In [31]:
df["Order_ID"].value_counts().head(20)

Order_ID
ORD004641    2
ORD002039    2
ORD000036    2
ORD010542    2
ORD011696    2
ORD002702    2
ORD010917    2
ORD007434    2
ORD005960    2
ORD008451    2
ORD006284    2
ORD001891    2
ORD003133    2
ORD008191    2
ORD000136    2
ORD005846    2
ORD010283    2
ORD011769    2
ORD005934    2
ORD009199    2
Name: count, dtype: int64

In [32]:
df[df["Order_ID"]=="ORD005846"]

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating
3992,ORD005846,CUST00409,12-24-2025,Sports,Cricket Bat,1,44.15,0.0,cod,Brisbane,AU,Pending,NaN
8131,ORD005846,CUST00409,12-24-2025,Sports,Cricket Bat,1,44.15,0.0,cod,Brisbane,AU,Pending,NaN

In [33]:
df["Payment_Method"].head()

0         Net Banking
1          NetBanking
2          DEBIT CARD
3    Cash on Delivery
4         Credit_Card
Name: Payment_Method, dtype: object

In [34]:
df["Payment_Method"].nunique()

20

In [35]:
df["Payment_Method"].value_counts(dropna=False)

Payment_Method
paypal              709
net banking         708
PayPal              695
UPI                 692
Net Banking         690
DEBIT CARD          680
NetBanking          658
U.P.I               651
Pay Pal             649
debit card          632
Debit Card          627
upi                 622
COD                 542
CREDIT CARD         538
cash on delivery    531
cod                 525
Credit_Card         517
credit card         508
Cash on Delivery    503
Credit Card         503
Name: count, dtype: int64

In [38]:
df["Order_Date"].nunique()

4229

In [41]:
df["Order_Date"].value_counts(dropna=False)

Order_Date
09-07-2024     12
25/07/2024     11
04-15-2025     10
08 Jun 2026     9
16 Oct 2024     9
               ..
2025/07/23      1
08 Apr 2025     1
24/04/2024      1
2026-05-23      1
05-01-2026      1
Name: count, Length: 4229, dtype: int64

In [42]:
df[df["Quantity"] <= 0][
    ["Order_ID", "Quantity", "Order_Status", "Product_Name"]
].head(20)

       Order_ID  Quantity Order_Status        Product_Name
197   ORD006541        -1     Returned       Running Shoes
265   ORD007225         0    Delivered        Dumbbell Set
285   ORD000653        -1    Delivered          Sunglasses
339   ORD008111         0    Delivered            Yoga Mat
378   ORD010769        -1    Delivered          Smartwatch
396   ORD004691        -1      Pending   Storage Organizer
421   ORD011689        -1    Delivered       LED Desk Lamp
510   ORD007890         0    Delivered            Football
664   ORD011724        -1    Delivered      Cycling Helmet
666   ORD003026         0     Returned            Yoga Mat
683   ORD003507        -1      Pending       Puzzle 1000pc
698   ORD005720         0    Delivered      Green Tea Pack
821   ORD009349         0     Returned          Hair Dryer
1043  ORD000199        -1    Delivered              Webcam
1046  ORD002804        -1    Delivered        Dumbbell Set
1126  ORD006912        -1    Delivered     Ceramic Mug Set
1140  ORD007650        -1    Delivered  Remote Control Car
1153  ORD003734        -1     Returned           Air Fryer
1280  ORD009863         0    Delivered        Olive Oil 1L
1310  ORD009219        -1      Shipped          Smartwatch

In [45]:
df[df["Unit_Price_USD"] <= 0][
    ["Order_ID", "Product_Name", "Quantity", "Unit_Price_USD"]
]

Empty DataFrame
Columns: [Order_ID, Product_Name, Quantity, Unit_Price_USD]
Index: []